version: '3'

services:

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    depends_on:
      - node-sharex-server
    ports:
      - "8080:80"
    networks:
      - app-network

  node-sharex-server:
    image: node-sharex-server:latest
    build:
      context: ../
    networks:
      - app-network

networks:
  app-network:
    driver: bridge